# Basic application settings
replicaCount: 1

image:
  repository: your-docker-image-repo/palworld
  tag: "latest"
  pullPolicy: IfNotPresent


# Security context for running the containers
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001


# Resource requests and limits
resources:
  requests:
    cpu: 500m
    memory: 1024Mi


# Environment variables for application configuration
env:
  PLAYERS: 10
  MULTITHREADING: "false"
  COMMUNITY: "false"
  UPDATE_ON_BOOT: "true"
  PORT: 27015
  ARM_DEVICE: "rpi4-pre3"
  PUBLIC_PORT: 8211


# Configuration for persistent storage
persistence:
  enabled: true
  serverdir:
    existingClaim: ""
    storageClass: "default"
    size: "10Gi"


# Service configuration (ports)
service:
  ports:
    query:
      tcp: 27015
      udp: 27015
    game:
      tcp: 8211
      udp: 8211


# PalWorldSettings.ini content
palWorldSettings:
  content: |
    [/Script/Pal.PalGameWorldSettings]
    OptionSettings=(Difficulty=1,DayTimeSpeedRate=1.0,NightTimeSpeedRate=1.0,ExpRate=1.0,PalCaptureRate=1.0,PalSpawnNumRate=1.0,CollectionDropRate=1.0,CollectionObjectHpRate=1.0,CollectionObjectRespawnSpeedRate=1.0,EnemyDropItemRate=1.0,WorkSpeedRate=1.0,PlayerDamageRateAttack=1.0,PlayerDamageRateDefense=1.0,PlayerStomachDecreaceRate=1.0,PlayerStaminaDecreaceRate=1.0,PlayerAutoHPRegeneRate=1.0,PlayerAutoHpRegeneRateInSleep=1.0,PalDamageRateAttack=1.0,PalDamageRateDefense=1.0,PalStomachDecreaceRate=1.0,PalStaminaDecreaceRate=1.0,PalAutoHPRegeneRate=1.0,PalAutoHpRegeneRateInSleep=1.0,BuildObjectDamageRate=1.0,BuildObjectDeteriorationDamageRate=1.0,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.0,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.0,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.0,ServerName=MyPaltopia,ServerDescription=,PublicPort=8211,RCONEnabled=False,RCONPort=25575,Region=,bUseAuth=True,BanListURL=https://api.palworldgame.com/api/banlist.txt)


# Secrets for secure information
secrets:
  ADMIN_PASSWORD: "D0n01tRyTh4t"
  SERVER_PASSWORD: ""
  PUBLIC_IP: ""


# Engine.ini content
engineConfig:
  content: |
    [Core.System]
    Paths=../../../Engine/Content
    Paths=%GAMEDIR%Content
    Paths=../../../Engine/Plugins/2D/Paper2D/Content
    Paths=../../../Engine/Plugins/Animation/ControlRigSpline/Content
    Paths=../../../Engine/Plugins/Animation/ControlRig/Content
    Paths=../../../Engine/Plugins/Animation/IKRig/Content
    Paths=../../../Engine/Plugins/Animation/MotionWarping/Content
    Paths=../../../Engine/Plugins/Bridge/Content
    Paths=../../../Engine/Plugins/Compositing/Composure/Content
    Paths=../../../Engine/Plugins/Compositing/OpenColorIO/Content
    Paths=../../../Engine/Plugins/Developer/AnimationSharing/Content
    Paths=../../../Engine/Plugins/Developer/Concert/ConcertSync/ConcertSyncClient/Content
    Paths=../../../Engine/Plugins/Editor/BlueprintHeaderView/Content
    Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
    Paths=../../../Engine/Plugins/Editor/ModelingToolsEditorMode/Content
    Paths=../../../Engine/Plugins/Editor/ObjectMixer/LightMixer/Content
    Paths=../../../Engine/Plugins/Editor/ObjectMixer/ObjectMixer/Content
    Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
    Paths=../../../Engine/Plugins/Enterprise/DatasmithContent/Content
    Paths=../../../Engine/Plugins/Enterprise/GLTFExporter/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosCaching/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
    Paths=../../../Engine/Plugins/Experimental/CommonUI/Content
    Paths=../../../Engine/Plugins/Experimental/Dataflow/Content
    Paths=../../../Engine/Plugins/Experimental/FullBodyIK/Content
    Paths=../../../Engine/Plugins/Experimental/GeometryCollectionPlugin/Content
    Paths=../../../Engine/Plugins/Experimental/GeometryFlow/Content
    Paths=../../../Engine/Plugins/Experimental/ImpostorBaker/Content
    Paths=../../../Engine/Plugins/Experimental/Landmass/Content
    Paths=../../../Engine/Plugins/Experimental/MeshLODToolset/Content
    Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
    Paths=../../../Engine/Plugins/Experimental/StaticMeshEditorModeling/Content
    Paths=../../../Engine/Plugins/Experimental/UVEditor/Content
    Paths=../../../Engine/Plugins/Experimental/Volumetrics/Content
    Paths=../../../Engine/Plugins/Experimental/Water/Content
    Paths=../../../Engine/Plugins/FX/Niagara/Content
    Paths=../../../Engine/Plugins/JsonBlueprintUtilities/Content
    Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
    Paths=../../../Engine/Plugins/Media/MediaPlate/Content
    Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
    Paths=../../../Engine/Plugins/PivotTool/Content
    Paths=../../../Engine/Plugins/PlacementTools/Content
    Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
    Paths=../../../Engine/Plugins/Runtime/AudioWidgets/Content
    Paths=../../../Engine/Plugins/Runtime/GeometryProcessing/Content
    Paths=../../../Engine/Plugins/Runtime/Metasound/Content
    Paths=../../../Engine/Plugins/Runtime/ResonanceAudio/Content
    Paths=../../../Engine/Plugins/Runtime/SunPosition/Content
    Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
    Paths=../../../Engine/Plugins/Runtime/WaveTable/Content
    Paths=../../../Engine/Plugins/Runtime/WebBrowserWidget/Content
    Paths=../../../Engine/Plugins/SkyCreatorPlugin/Content
    Paths=../../../Engine/Plugins/VirtualProduction/CameraCalibrationCore/Content
    Paths=../../../Engine/Plugins/VirtualProduction/LiveLinkCamera/Content
    Paths=../../../Engine/Plugins/VirtualProduction/Takes/Content
    Paths=../../../Engine/Plugins/Web/HttpBlueprint/Content
    Paths=../../../Pal/Plugins/DLSS/Content
    Paths=../../../Pal/Plugins/EffectsChecker/Content
    Paths=../../../Pal/Plugins/HoudiniEngine/Content
    Paths=../../../Pal/Plugins/PPSkyCreatorPlugin/Content
    Paths=../../../Pal/Plugins/PocketpairUser/Content
    Paths=../../../Pal/Plugins/SpreadSheetToCsv/Content
    Paths=../../../Pal/Plugins/Wwise/Content
    [/Script/OnlineSubsystemUtils.IpNetDriver]
    NetServerMaxTickRate=15
    LanServerMaxTickRate=15
    MaxNetTickRate=15
    [/script/engine.player]
    ConfiguredInternetSpeed=104857600
    ConfiguredLanSpeed=104857600
    [/script/socketsubsystemepic.epicnetdriver]
    MaxClientRate=104857600
    MaxInternetClientRate=104857600
    [/Script/Engine.Engine]
    bSmoothFrameRate=true
    bUseFixedFrameRate=true
    SmoothedFrameRateRange=(LowerBound=(Type=Inclusive,Value=30.000000),UpperBound=(Type=Exclusive,Value=120.000000))
    MinDesiredFrameRate=60.000000
    NetClientTicksPerSecond=120
    [/script/engine.garbagecollectionsettings]
    TimeBetweenPurgingPendingKillObjects=45
