replicaCount: 1

image:
  repository: your-docker-image-repo/palworld
  pullPolicy: IfNotPresent
  tag: "latest"

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

resources:
  requests:
    cpu: 500m
    memory: 1024Mi

persistence:
  enabled: true
  serverdir:
    existingClaim: ""

service:
  nodePorts:
    queryPortTCP: null
    queryPortUDP: null
    gamePortTCP: null
    gamePortUDP: null

env:
  PUID: 1000
  PLAYERS: 10
  MULTITHREADING: "false"
  COMMUNITY: "false"
  UPDATE_ON_BOOT: "true"
  PORT: 27015

palWorldSettings:
  Difficulty: None
  DayTimeSpeedRate: 1.000000
  NightTimeSpeedRate: 1.000000
  ExpRate: 1.000000
  PalCaptureRate: 1.000000
  PalSpawnNumRate: 1.000000
  PalDamageRateAttack: 1.000000
  PalDamageRateDefense: 1.000000
  PlayerDamageRateAttack: 1.000000
  PlayerDamageRateDefense: 1.000000
  PlayerStomachDecreaceRate: 1.000000
  PlayerStaminaDecreaceRate: 1.000000
  PlayerAutoHPRegeneRate: 1.000000
  PlayerAutoHpRegeneRateInSleep: 1.000000
  PalStomachDecreaceRate: 1.000000
  PalStaminaDecreaceRate: 1.000000
  PalAutoHPRegeneRate: 1.000000
  PalAutoHpRegeneRateInSleep: 1.000000
  BuildObjectDamageRate: 1.000000
  BuildObjectDeteriorationDamageRate: 1.000000
  CollectionDropRate: 1.000000
  CollectionObjectHpRate: 1.000000
  CollectionObjectRespawnSpeedRate: 1.000000
  EnemyDropItemRate: 1.000000
  DeathPenalty: All
  bEnablePlayerToPlayerDamage: False
  bEnableFriendlyFire: False
  bEnableInvaderEnemy: True
  bActiveUNKO: False
  bEnableAimAssistPad: True
  bEnableAimAssistKeyboard: False
  DropItemMaxNum: 3000
  DropItemMaxNum_UNKO: 100
  BaseCampMaxNum: 128
  BaseCampWorkerMaxNum: 15
  DropItemAliveMaxHours: 1.000000
  bAutoResetGuildNoOnlinePlayers: False
  AutoResetGuildTimeNoOnlinePlayers: 72.000000
  GuildPlayerMaxNum: 20
  PalEggDefaultHatchingTime: 72.000000
  WorkSpeedRate: 1.000000
  bIsMultiplay: False
  bIsPvP: False
  bCanPickupOtherGuildDeathPenaltyDrop: False
  bEnableNonLoginPenalty: True
  bEnableFastTravel: True
  bIsStartLocationSelectByMap: True
  bExistPlayerAfterLogout: False
  bEnableDefenseOtherGuildPlayer: False
  CoopPlayerMaxNum: 4
  ServerPlayerMaxNum: 32
  ServerName: "MyPaltopia"
  ServerDescription: ""
  PublicPort: 8211
  RCONEnabled: False
  RCONPort: 25575
  Region: ""
  bUseAuth: True
  BanListURL: "https://api.palworldgame.com/api/banlist.txt"

secrets:
  AdminPassword: "D0n01tRyTh4t"
  ServerPassword: ""
  PublicIP:
