apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palworld.fullname" . }}
data:
  COMMUNITY: "{{ .Values.env.COMMUNITY }}"
  UPDATE_ON_BOOT: "{{ .Values.env.UPDATE_ON_BOOT }}"
  PalWorldSettings.ini: |
    {{- .Values.palWorldSettings.content | nindent 4 }}
  Engine.ini: |
    {{- .Values.engineConfig.content | nindent 4 }}
