apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palworld.fullname" . }}
data:
  COMMUNITY: "{{ .Values.env.COMMUNITY }}"
  UPDATE_ON_BOOT: "{{ .Values.env.UPDATE_ON_BOOT }}"
  PalWorldSettings.ini: |
    [/Script/Pal.PalGameWorldSettings]
    OptionSettings=(Difficulty={{ .Values.palWorldSettings.Difficulty }},DayTimeSpeedRate={{ .Values.palWorldSettings.DayTimeSpeedRate }},NightTimeSpeedRate={{ .Values.palWorldSettings.NightTimeSpeedRate }},ExpRate={{ .Values.palWorldSettings.ExpRate }},PalCaptureRate={{ .Values.palWorldSettings.PalCaptureRate }},PalSpawnNumRate={{ .Values.palWorldSettings.PalSpawnNumRate }},PalDamageRateAttack={{ .Values.palWorldSettings.PalDamageRateAttack }},PalDamageRateDefense={{ .Values.palWorldSettings.PalDamageRateDefense }},PlayerDamageRateAttack={{ .Values.palWorldSettings.PlayerDamageRateAttack }},PlayerDamageRateDefense={{ .Values.palWorldSettings.PlayerDamageRateDefense }},PlayerStomachDecreaceRate={{ .Values.palWorldSettings.PlayerStomachDecreaceRate }},PlayerStaminaDecreaceRate={{ .Values.palWorldSettings.PlayerStaminaDecreaceRate }},PlayerAutoHPRegeneRate={{ .Values.palWorldSettings.PlayerAutoHPRegeneRate }},PlayerAutoHpRegeneRateInSleep={{ .Values.palWorldSettings.PlayerAutoHpRegeneRateInSleep }},PalStomachDecreaceRate={{ .Values.palWorldSettings.PalStomachDecreaceRate }},PalStaminaDecreaceRate={{ .Values.palWorldSettings.PalStaminaDecreaceRate }},PalAutoHPRegeneRate={{ .Values.palWorldSettings.PalAutoHPRegeneRate }},PalAutoHpRegeneRateInSleep={{ .Values.palWorldSettings.PalAutoHpRegeneRateInSleep }},BuildObjectDamageRate={{ .Values.palWorldSettings.BuildObjectDamageRate }},BuildObjectDeteriorationDamageRate={{ .Values.palWorldSettings.BuildObjectDeteriorationDamageRate }},CollectionDropRate={{ .Values.palWorldSettings.CollectionDropRate }},CollectionObjectHpRate={{ .Values.palWorldSettings.CollectionObjectHpRate }},CollectionObjectRespawnSpeedRate={{ .Values.palWorldSettings.CollectionObjectRespawnSpeedRate }},EnemyDropItemRate={{ .Values.palWorldSettings.EnemyDropItemRate }},DeathPenalty={{ .Values.palWorldSettings.DeathPenalty }},bEnablePlayerToPlayerDamage={{ .Values.palWorldSettings.bEnablePlayerToPlayerDamage }},bEnableFriendlyFire={{ .Values.palWorldSettings.bEnableFriendlyFire }},bEnableInvaderEnemy={{ .Values.palWorldSettings.bEnableInvaderEnemy }},bActiveUNKO={{ .Values.palWorldSettings.bActiveUNKO }},bEnableAimAssistPad={{ .Values.palWorldSettings.bEnableAimAssistPad }},bEnableAimAssistKeyboard={{ .Values.palWorldSettings.bEnableAimAssistKeyboard }},DropItemMaxNum={{ .Values.palWorldSettings.DropItemMaxNum }},DropItemMaxNum_UNKO={{ .Values.palWorldSettings.DropItemMaxNum_UNKO }},BaseCampMaxNum={{ .Values.palWorldSettings.BaseCampMaxNum }},BaseCampWorkerMaxNum={{ .Values.palWorldSettings.BaseCampWorkerMaxNum }},DropItemAliveMaxHours={{ .Values.palWorldSettings.DropItemAliveMaxHours }},bAutoResetGuildNoOnlinePlayers={{ .Values.palWorldSettings.bAutoResetGuildNoOnlinePlayers }},AutoResetGuildTimeNoOnlinePlayers={{ .Values.palWorldSettings.AutoResetGuildTimeNoOnlinePlayers }},GuildPlayerMaxNum={{ .Values.palWorldSettings.GuildPlayerMaxNum }},PalEggDefaultHatchingTime={{ .Values.palWorldSettings.PalEggDefaultHatchingTime }},WorkSpeedRate={{ .Values.palWorldSettings.WorkSpeedRate }},bIsMultiplay={{ .Values.palWorldSettings.bIsMultiplay }},bIsPvP={{ .Values.palWorldSettings.bIsPvP }},bCanPickupOtherGuildDeathPenaltyDrop={{ .Values.palWorldSettings.bCanPickupOtherGuildDeathPenaltyDrop }},bEnableNonLoginPenalty={{ .Values.palWorldSettings.bEnableNonLoginPenalty }},bEnableFastTravel={{ .Values.palWorldSettings.bEnableFastTravel }},bIsStartLocationSelectByMap={{ .Values.palWorldSettings.bIsStartLocationSelectByMap }},bExistPlayerAfterLogout={{ .Values.palWorldSettings.bExistPlayerAfterLogout }},bEnableDefenseOtherGuildPlayer={{ .Values.palWorldSettings.bEnableDefenseOtherGuildPlayer }},CoopPlayerMaxNum={{ .Values.palWorldSettings.CoopPlayerMaxNum }},ServerPlayerMaxNum={{ .Values.palWorldSettings.ServerPlayerMaxNum }},ServerName={{ .Values.palWorldSettings.ServerName }},ServerDescription={{ .Values.palWorldSettings.ServerDescription }},AdminPassword=ADMIN_PASSWORD,ServerPassword=SERVER_PASSWORD,PublicPort={{ .Values.palWorldSettings.PublicPort }},PublicIP=PUBLIC_IP,RCONEnabled={{ .Values.palWorldSettings.RCONEnabled }},RCONPort={{ .Values.palWorldSettings.RCONPort }},Region={{ .Values.palWorldSettings.Region }},bUseAuth={{ .Values.palWorldSettings.bUseAuth }},BanListURL={{ .Values.palWorldSettings.BanListURL }})
  {{- if .Values.gameUserSettings.DedicatedServerName }}
  GameUserSettings.ini: |
    [/Script/Pal.PalGameLocalSettings]
    AudioSettings=(Master=0.500000,BGM=1.000000,SE=1.000000,PalVoice=1.000000,HumanVoice=1.000000,Ambient=1.000000,UI=1.000000)
    GraphicsLevel=None
    DefaultGraphicsLevel=None
    bRunedBenchMark=False
    bHasAppliedUserSetting=False
    DedicatedServerName={{ .Values.gameUserSettings.DedicatedServerName }}
    AntiAliasingType=AAM_TSR
    DLSSMode=Performance
    GraphicsCommonQuality=0
  {{- end }}
  Engine.ini: |
    [Core.System]
    Paths=../../../Engine/Content
    Paths=%GAMEDIR%Content
    Paths=../../../Engine/Plugins/2D/Paper2D/Content
    Paths=../../../Engine/Plugins/Animation/ControlRigSpline/Content
    Paths=../../../Engine/Plugins/Animation/ControlRig/Content
    Paths=../../../Engine/Plugins/Animation/IKRig/Content
    Paths=../../../Engine/Plugins/Animation/MotionWarping/Content
    Paths=../../../Engine/Plugins/Bridge/Content
    Paths=../../../Engine/Plugins/Compositing/Composure/Content
    Paths=../../../Engine/Plugins/Compositing/OpenColorIO/Content
    Paths=../../../Engine/Plugins/Developer/AnimationSharing/Content
    Paths=../../../Engine/Plugins/Developer/Concert/ConcertSync/ConcertSyncClient/Content
    Paths=../../../Engine/Plugins/Editor/BlueprintHeaderView/Content
    Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
    Paths=../../../Engine/Plugins/Editor/ModelingToolsEditorMode/Content
    Paths=../../../Engine/Plugins/Editor/ObjectMixer/LightMixer/Content
    Paths=../../../Engine/Plugins/Editor/ObjectMixer/ObjectMixer/Content
    Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
    Paths=../../../Engine/Plugins/Enterprise/DatasmithContent/Content
    Paths=../../../Engine/Plugins/Enterprise/GLTFExporter/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosCaching/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
    Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
    Paths=../../../Engine/Plugins/Experimental/CommonUI/Content
    Paths=../../../Engine/Plugins/Experimental/Dataflow/Content
    Paths=../../../Engine/Plugins/Experimental/FullBodyIK/Content
    Paths=../../../Engine/Plugins/Experimental/GeometryCollectionPlugin/Content
    Paths=../../../Engine/Plugins/Experimental/GeometryFlow/Content
    Paths=../../../Engine/Plugins/Experimental/ImpostorBaker/Content
    Paths=../../../Engine/Plugins/Experimental/Landmass/Content
    Paths=../../../Engine/Plugins/Experimental/MeshLODToolset/Content
    Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
    Paths=../../../Engine/Plugins/Experimental/StaticMeshEditorModeling/Content
    Paths=../../../Engine/Plugins/Experimental/UVEditor/Content
    Paths=../../../Engine/Plugins/Experimental/Volumetrics/Content
    Paths=../../../Engine/Plugins/Experimental/Water/Content
    Paths=../../../Engine/Plugins/FX/Niagara/Content
    Paths=../../../Engine/Plugins/JsonBlueprintUtilities/Content
    Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
    Paths=../../../Engine/Plugins/Media/MediaPlate/Content
    Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
    Paths=../../../Engine/Plugins/PivotTool/Content
    Paths=../../../Engine/Plugins/PlacementTools/Content
    Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
    Paths=../../../Engine/Plugins/Runtime/AudioWidgets/Content
    Paths=../../../Engine/Plugins/Runtime/GeometryProcessing/Content
    Paths=../../../Engine/Plugins/Runtime/Metasound/Content
    Paths=../../../Engine/Plugins/Runtime/ResonanceAudio/Content
    Paths=../../../Engine/Plugins/Runtime/SunPosition/Content
    Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
    Paths=../../../Engine/Plugins/Runtime/WaveTable/Content
    Paths=../../../Engine/Plugins/Runtime/WebBrowserWidget/Content
    Paths=../../../Engine/Plugins/SkyCreatorPlugin/Content
    Paths=../../../Engine/Plugins/VirtualProduction/CameraCalibrationCore/Content
    Paths=../../../Engine/Plugins/VirtualProduction/LiveLinkCamera/Content
    Paths=../../../Engine/Plugins/VirtualProduction/Takes/Content
    Paths=../../../Engine/Plugins/Web/HttpBlueprint/Content
    Paths=../../../Pal/Plugins/DLSS/Content
    Paths=../../../Pal/Plugins/EffectsChecker/Content
    Paths=../../../Pal/Plugins/HoudiniEngine/Content
    Paths=../../../Pal/Plugins/PPSkyCreatorPlugin/Content
    Paths=../../../Pal/Plugins/PocketpairUser/Content
    Paths=../../../Pal/Plugins/SpreadSheetToCsv/Content
    Paths=../../../Pal/Plugins/Wwise/Content

    [/Script/OnlineSubsystemUtils.IpNetDriver]
    NetServerMaxTickRate={{ .Values.engineConfig.netServerMaxTickRate }}
    
    [/Script/Engine.Engine]
    bSmoothFrameRate={{ .Values.engineConfig.smoothFrameRate | lower }}
    bUseFixedFrameRate={{ .Values.engineConfig.useFixedFrameRate | lower }}
    FixedFrameRate={{ .Values.engineConfig.fixedFrameRate }}.000000