apiVersion: v1
kind: ConfigMap
metadata:
  name: { ? { include "palworld.fullname" . } }
data:
  PLAYERS: "{{ default 10 .Values.env.PLAYERS }}"
  MULTITHREADING: "{{ .Values.env.MULTITHREADING }}"
  COMMUNITY: "{{ .Values.env.COMMUNITY }}"
  UPDATE_ON_BOOT: "{{ .Values.env.UPDATE_ON_BOOT }}"
  PORT: "{{ .Values.env.PORT }}"
  DedicatedServerName: "{{ .Values.gameUserSettings.DedicatedServerName }}"
  PalWorldSettings.ini: |
    [General]
    ServerName={{ .Values.palWorldSettings.ServerName }}
    ServerDescription={{ .Values.palWorldSettings.ServerDescription }}
    ServerPlayerMaxNum={{ .Values.palWorldSettings.ServerPlayerMaxNum }}
    CoopPlayerMaxNum={{ .Values.palWorldSettings.CoopPlayerMaxNum }}
    PublicPort={{ .Values.palWorldSettings.PublicPort }}
    RCONEnabled={{ .Values.palWorldSettings.RCONEnabled }}
    RCONPort={{ .Values.palWorldSettings.RCONPort }}
    Region={{ .Values.palWorldSettings.Region }}
    bUseAuth={{ .Values.palWorldSettings.bUseAuth }}
    BanListURL={{ .Values.palWorldSettings.BanListURL }}

    [Rates]
    Difficulty={{ .Values.palWorldSettings.Difficulty }}
    DayTimeSpeedRate={{ .Values.palWorldSettings.DayTimeSpeedRate }}
    NightTimeSpeedRate={{ .Values.palWorldSettings.NightTimeSpeedRate }}
    ExpRate={{ .Values.palWorldSettings.ExpRate }}
    PalCaptureRate={{ .Values.palWorldSettings.PalCaptureRate }}
    PalSpawnNumRate={{ .Values.palWorldSettings.PalSpawnNumRate }}
    CollectionDropRate={{ .Values.palWorldSettings.CollectionDropRate }}
    CollectionObjectHpRate={{ .Values.palWorldSettings.CollectionObjectHpRate }}
    CollectionObjectRespawnSpeedRate={{ .Values.palWorldSettings.CollectionObjectRespawnSpeedRate }}
    EnemyDropItemRate={{ .Values.palWorldSettings.EnemyDropItemRate }}
    WorkSpeedRate={{ .Values.palWorldSettings.WorkSpeedRate }}

    [Players]
    PlayerDamageRateAttack={{ .Values.palWorldSettings.PlayerDamageRateAttack }}
    PlayerDamageRateDefense={{ .Values.palWorldSettings.PlayerDamageRateDefense }}
    PlayerStomachDecreaceRate={{ .Values.palWorldSettings.PlayerStomachDecreaceRate }}
    PlayerStaminaDecreaceRate={{ .Values.palWorldSettings.PlayerStaminaDecreaceRate }}
    PlayerAutoHPRegeneRate={{ .Values.palWorldSettings.PlayerAutoHPRegeneRate }}
    PlayerAutoHpRegeneRateInSleep={{ .Values.palWorldSettings.PlayerAutoHpRegeneRateInSleep }}
    PalDamageRateAttack={{ .Values.palWorldSettings.PalDamageRateAttack }}
    PalDamageRateDefense={{ .Values.palWorldSettings.PalDamageRateDefense }}
    PalStomachDecreaceRate={{ .Values.palWorldSettings.PalStomachDecreaceRate }}
    PalStaminaDecreaceRate={{ .Values.palWorldSettings.PalStaminaDecreaceRate }}
    PalAutoHPRegeneRate={{ .Values.palWorldSettings.PalAutoHPRegeneRate }}
    PalAutoHpRegeneRateInSleep={{ .Values.palWorldSettings.PalAutoHpRegeneRateInSleep }}

    [Building]
    BuildObjectDamageRate={{ .Values.palWorldSettings.BuildObjectDamageRate }}
    BuildObjectDeteriorationDamageRate={{ .Values.palWorldSettings.BuildObjectDeteriorationDamageRate }}

    [Mechanics]
    DeathPenalty={{ .Values.palWorldSettings.DeathPenalty }}
    bEnablePlayerToPlayerDamage={{ .Values.palWorldSettings.bEnablePlayerToPlayerDamage }}
    bEnableFriendlyFire={{ .Values.palWorldSettings.bEnableFriendlyFire }}
    bEnableInvaderEnemy={{ .Values.palWorldSettings.bEnableInvaderEnemy }}
    bActiveUNKO={{ .Values.palWorldSettings.bActiveUNKO }}
    bEnableAimAssistPad={{ .Values.palWorldSettings.bEnableAimAssistPad }}
    bEnableAimAssistKeyboard={{ .Values.palWorldSettings.bEnableAimAssistKeyboard }}
    bIsMultiplay={{ .Values.palWorldSettings.bIsMultiplay }}
    bIsPvP={{ .Values.palWorldSettings.bIsPvP }}
    bCanPickupOtherGuildDeathPenaltyDrop={{ .Values.palWorldSettings.bCanPickupOtherGuildDeathPenaltyDrop }}
    bEnableNonLoginPenalty={{ .Values.palWorldSettings.bEnableNonLoginPenalty }}
    bEnableFastTravel={{ .Values.palWorldSettings.bEnableFastTravel }}
    bIsStartLocationSelectByMap={{ .Values.palWorldSettings.bIsStartLocationSelectByMap }}
    bExistPlayerAfterLogout={{ .Values.palWorldSettings.bExistPlayerAfterLogout }}
    bEnableDefenseOtherGuildPlayer={{ .Values.palWorldSettings.bEnableDefenseOtherGuildPlayer }}

    [Server]
    DropItemMaxNum={{ .Values.palWorldSettings.DropItemMaxNum }}
    DropItemMaxNum_UNKO={{ .Values.palWorldSettings.DropItemMaxNum_UNKO }}
    BaseCampMaxNum={{ .Values.palWorldSettings.BaseCampMaxNum }}
    BaseCampWorkerMaxNum={{ .Values.palWorldSettings.BaseCampWorkerMaxNum }}
    DropItemAliveMaxHours={{ .Values.palWorldSettings.DropItemAliveMaxHours }}
    bAutoResetGuildNoOnlinePlayers={{ .Values.palWorldSettings.bAutoResetGuildNoOnlinePlayers }}
    AutoResetGuildTimeNoOnlinePlayers={{ .Values.palWorldSettings.AutoResetGuildTimeNoOnlinePlayers }}
    GuildPlayerMaxNum={{ .Values.palWorldSettings.GuildPlayerMaxNum }}
    PalEggDefaultHatchingTime={{ .Values.palWorldSettings.PalEggDefaultHatchingTime }}

  Engine.ini: |
    [Core.System]
    NetServerMaxTickRate={{ .Values.engineConfig.netServerMaxTickRate }}
    bSmoothFrameRate={{ .Values.engineConfig.smoothFrameRate }}
    bUseFixedFrameRate={{ .Values.engineConfig.useFixedFrameRate }}
    FixedFrameRate={{ .Values.engineConfig.fixedFrameRate }}
