apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "palworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "palworld.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: gameport
              containerPort: {{ .Values.env.PORT | default 27015 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: saved-data
              mountPath: /palworld/Saved
            - name: log-data
              mountPath: /palworld/Logs
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: PLAYERS
              value: "{{ .Values.env.PLAYERS }}"
            - name: MULTITHREADING
              value: "{{ .Values.env.MULTITHREADING }}"
            - name: COMMUNITY
              value: "{{ .Values.env.COMMUNITY }}"
            - name: PUBLIC_IP
              value: "{{ .Values.env.PUBLIC_IP }}"
            - name: PUBLIC_PORT
              value: "{{ .Values.env.PUBLIC_PORT }}"
            - name: SERVER_PASSWORD
              value: "{{ .Values.env.SERVER_PASSWORD }}"
            - name: SERVER_NAME
              value: "{{ .Values.env.SERVER_NAME }}"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.env.ADMIN_PASSWORD }}"
            - name: UPDATE_ON_BOOT
              value: "{{ .Values.env.UPDATE_ON_BOOT }}"
      volumes:
        - name: saved-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.savedData.existingClaim }}
        - name: log-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.logData.existingClaim }}