apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "palworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "palworld.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: tcp-gameport
            containerPort: {{ .Values.palWorldSettings.PublicPort }}
            protocol: TCP
          - name: udp-gameport
            containerPort: {{ .Values.palWorldSettings.PublicPort }}
            protocol: UDP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: serverdir
            mountPath: /palworld
          - name: config
            mountPath: /tmp/PalWorldSettings.ini
            subPath: PalWorldSettings.ini
        envFrom:
          - configMapRef:
              name: {{ include "palworld.fullname" . }}
        env:
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "palworld.fullname" . }}
                key: ADMIN_PASSWORD
          - name: SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "palworld.fullname" . }}
                key: SERVER_PASSWORD
          - name: PUBLIC_IP
            valueFrom:
              secretKeyRef:
                name: {{ include "palworld.fullname" . }}
                key: PUBLIC_IP
      volumes:
        - name: serverdir
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.serverdir.existingClaim }}
        - name: config
          configMap:
            name: {{ include "palworld.fullname" . }}
            items:
              - key: PalWorldSettings.ini
                path: PalWorldSettings.ini
