apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "palworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "palworld.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: tcp-queryport
            containerPort: {{ .Values.env.PORT }}
            protocol: TCP
          - name: udp-queryport
            containerPort: {{ .Values.env.PORT }}
            protocol: UDP
          - name: tcp-gameport
            containerPort: {{ .Values.palWorldSettings.PublicPort }}
            protocol: TCP
          - name: udp-gameport
            containerPort: {{ .Values.palWorldSettings.PublicPort }}
            protocol: UDP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: serverdir
            mountPath: /palworld
          - name: config
            mountPath: /palworld/Pal/Saved/Config/LinuxServer
            readOnly: true
        env:
          - name: PLAYERS
            value: "{{ .Values.env.PLAYERS }}"
          - name: MULTITHREADING
            value: "{{ .Values.env.MULTITHREADING }}"
          - name: COMMUNITY
            value: "{{ .Values.env.COMMUNITY }}"
          - name: UPDATE_ON_BOOT
            value: "{{ .Values.env.UPDATE_ON_BOOT }}"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "palworld.fullname" . }}
                key: AdminPassword
          - name: SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "palworld.fullname" . }}
                key: ServerPassword
          - name: PUBLIC_IP
            valueFrom:
              secretKeyRef:
                name: {{ include "palworld.fullname" . }}
                key: PublicIP
          - name: ARM_DEVICE
            value: "{{ .Values.env.ARM_DEVICE }}"
      volumes:
        - name: serverdir
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.serverdir.existingClaim }}{{ .Values.persistence.serverdir.existingClaim }}{{ else }}{{ include "palworld.fullname" . }}-serverdir{{ end }}
        - name: config
          configMap:
            name: {{ include "palworld.fullname" . }}