apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "palworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "palworld.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
<<<<<<< HEAD
            - name: queryport
              containerPort: {{ .Values.env.PORT }}
              protocol: TCP
            - name: gameport
              containerPort: {{ .Values.env.PUBLIC_PORT }}
=======
            - name: tcp-queryport
              containerPort: {{ .Values.env.PORT }}
>>>>>>> 2aa418de817c98fd7f029a0cdcd9ed03fe80e748
              protocol: TCP
            - name: udp-queryport
              containerPort: {{ .Values.env.PORT }}
              protocol: UDP
            - name: tcp-gameport
              containerPort: {{ .Values.env.PUBLIC_PORT }}
              protocol: TCP
            - name: udp-gameport
              containerPort: {{ .Values.env.PUBLIC_PORT }}
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: serverdir
              mountPath: /palworld
          envFrom:
            - configMapRef:
                name: {{ include "palworld.fullname" . }}
            - secretRef:
                name: {{ include "palworld.fullname" . }}
      volumes:
        - name: serverdir
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.serverdir.existingClaim }}
