# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {? {include "palworld.fullname" .: ''} : ''}
type: Opaque
data:
  SERVER_PASSWORD: {? {.Values.env.SERVER_PASSWORD | b64enc | quote: ''} : ''}
  ADMIN_PASSWORD: {? {.Values.env.ADMIN_PASSWORD | b64enc | quote: ''} : ''}
