apiVersion: v1
kind: Secret
metadata:
  name: palworld-secret
type: Opaque
data:
  SERVER_PASSWORD: {{ default "" .Values.env.SERVER_PASSWORD | b64enc | quote }}
  ADMIN_PASSWORD: {{ default "" .Values.env.ADMIN_PASSWORD | b64enc | quote }}
