apiVersion: v1
kind: Secret
metadata:
  name: {{ include "palworld.fullname" . }}
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.secrets.AdminPassword | b64enc | quote }}
  SERVER_PASSWORD: {{ .Values.secrets.ServerPassword | b64enc | quote }}
  PUBLIC_IP: {{ .Values.secrets.PublicIP | b64enc | quote }}
