apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gameport
      protocol: TCP
      name: gameport
  selector:
    {{- include "palworld.selectorLabels" . | nindent 6 }}
