apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "palworld.selectorLabels" . | nindent 6 }}
  type: NodePort
  ports:
    - port: {{ .Values.service.ports.query.tcp }}
      targetPort: {{ .Values.service.ports.query.tcp }}
      protocol: TCP
      name: tcp-query
    - port: {{ .Values.service.ports.query.udp }}
      targetPort: {{ .Values.service.ports.query.udp }}
      protocol: UDP
      name: udp-query
    - port: {{ .Values.service.ports.game.tcp }}
      targetPort: {{ .Values.service.ports.game.tcp }}
      protocol: TCP
      name: tcp-game
    - port: {{ .Values.service.ports.game.udp }}
      targetPort: {{ .Values.service.ports.game.udp }}
      protocol: UDP
      name: udp-game
