apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "palworld.selectorLabels" . | nindent 6 }}
  type: NodePort
  ports:
    - port: {{ .Values.env.PORT }}
      targetPort: {{ .Values.env.PORT }}
      protocol: TCP
      name: tcp-queryport
      {{- if .Values.service.nodePorts.queryPortTCP }}
      nodePort: {{ .Values.service.nodePorts.queryPortTCP }}
      {{- end }}
    - port: {{ .Values.env.PORT }}
      targetPort: {{ .Values.env.PORT }}
      protocol: UDP
      name: udp-queryport
      {{- if .Values.service.nodePorts.queryPortUDP }}
      nodePort: {{ .Values.service.nodePorts.queryPortUDP }}
      {{- end }}
    - port: {{ .Values.palWorldSettings.PublicPort }}
      targetPort: {{ .Values.palWorldSettings.PublicPort }}
      protocol: TCP
      name: tcp-gameport
      {{- if .Values.service.nodePorts.gamePortTCP }}
      nodePort: {{ .Values.service.nodePorts.gamePortTCP }}
      {{- end }}
    - port: {{ .Values.palWorldSettings.PublicPort }}
      targetPort: {{ .Values.palWorldSettings.PublicPort }}
      protocol: UDP
      name: udp-gameport
      {{- if .Values.service.nodePorts.gamePortUDP }}
      nodePort: {{ .Values.service.nodePorts.gamePortUDP }}
      {{- end }}
    {{- include "palworld.selectorLabels" . | nindent 6 }}
