apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "palworld.selectorLabels" . | nindent 6 }}
  type: NodePort
  ports:
    - port: {{ .Values.palWorldSettings.PublicPort }}
      targetPort: {{ .Values.palWorldSettings.PublicPort }}
      protocol: TCP
      name: tcp-gameport
    - port: {{ .Values.palWorldSettings.PublicPort }}
      targetPort: {{ .Values.palWorldSettings.PublicPort }}
      protocol: UDP
      name: udp-gameport
    {{- include "palworld.selectorLabels" . | nindent 6 }}
