apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8211
      targetPort: 8211
      protocol: TCP
      name: gameport
  selector:
    {{- include "palworld.selectorLabels" . | nindent 6 }}
